INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Baruta',15);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Sucre',15);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Libertador',10);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Maracaibo',24);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Barquisimeto',13);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','El Tigre',2);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Guanare',18);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Paraguana',11);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Valle La Pascua',12);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Urena',20);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','San Felix',6);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Carora',13);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Acarigua',18);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Tariba',20);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Maracay',4);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Puerto Ordaz',6);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','San Cristobal',20);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Los Teques',15);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Anaco',2);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','San Casimiro',4);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','San Antonio',15);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','La Guaira',22);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Margarita',17);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Guanta',6);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Puerto La Cruz',6);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Merida',14);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Barinas',5);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Tucacas',11);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Costa Oriental',24);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','La Victoria',4);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Villa de Cura',4);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Ciudad Ojeda',24);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Ciudad Bolivar',6);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Barcelona',2);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','San Fernando',3);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Valencia',7);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Maiquetia',22);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Carupano',19);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Coro',11);
INSERT INTO Lugar (L_Tipo,L_Nombre,FK_L_ID) VALUES ('Municipio','Trujillo',21);