INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (0,'Sweet Shop','SweetShop',10);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (1,'Sweet Cafetal','Mini SweetShop',65);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (2,'Sweet Maracaibo','Mini SweetShop',28);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (3,'Sweet Barquisimeto','Mini SweetShop',29);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (4,'Sweet Tigre','Mini SweetShop',30);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (5,'Sweet Guanare','Mini SweetShop',31);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (6,'Sweet Paraguana','Mini SweetShop',32);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (7,'Sweet Pascua','Mini SweetShop',33);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (8,'Sweet Urena','Mini SweetShop',34);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (9,'Sweet San Felix','Mini SweetShop',35);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (10,'Sweet Carora','Mini SweetShop',36);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (11,'Sweet Acarigua','Mini SweetShop',37);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (12,'Sweet Tariba','Mini SweetShop',38);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (13,'Sweet Petare','Mini SweetShop',66);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (14,'Sweet Maracay','Mini SweetShop',39);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (15,'Sweet Ordaz','Mini SweetShop',40);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (16,'Sweet San Cristobal','Mini SweetShop',41);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (17,'Sweet Los Teques','Mini SweetShop',42);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (18,'Sweet Anaco','Mini SweetShop',43);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (19,'Sweet Casimiro','Mini SweetShop',44);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (20,'Sweet San Antonio','Mini SweetShop',45);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (21,'Sweet Antimano','Mini SweetShop',67);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (22,'Sweet La Guaira','Mini SweetShop',46);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (23,'Sweet Margarita','Mini SweetShop',47);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (24,'Sweet Guanta','Mini SweetShop',48);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (25,'Sweet La Cruz','Mini SweetShop',49);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (26,'Sweet Merida','Mini SweetShop',50);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (27,'Sweet Barinas','Mini SweetShop',51);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (28,'Sweet Tucacas','Mini SweetShop',52);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (29,'Sweet Costa Lago','Mini SweetShop',53);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (30,'Sweet Victoria','Mini SweetShop',54);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (31,'Sweet Cura','Mini SweetShop',55);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (32,'Sweet Ojeda','Mini SweetShop',56);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (33,'Sweet Bolivar','Mini SweetShop',57);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (34,'Sweet Barcelona','Mini SweetShop',58);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (35,'Sweet Apure','Mini SweetShop',59);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (36,'Sweet Valencia','Mini SweetShop',60);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (37,'Sweet Maiquetia','Mini SweetShop',61);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (38,'Sweet Carupano','Mini SweetShop',62);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (39,'Sweet Coro','Mini SweetShop',63);
INSERT INTO Tienda (TI_ID,TI_Nombre,TI_Tipo,FK_L_ID) VALUES (40,'Sweet Trujillo','Mini SweetShop',64);