INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Amazonas');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Anzoategui');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Apure');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Aragua');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Barinas');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Bolivar');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Carabobo');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Cojedes');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Delta Amacuro');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Distrito Capital');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Falcon');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Guarico');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Lara');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Merida');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Miranda');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Monagas');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Nueva Esparta');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Portuguesa');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Sucre');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Tachira');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Trujillo');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Vargas');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Yaracuy');
INSERT INTO Lugar (L_Tipo,L_Nombre) VALUES ('Estado','Zulia');